services:
  projectflow.api:
    image: ${DOCKER_REGISTRY-}projectflowapi
    build:
      context: .
      dockerfile: ProjectFlow.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    environment:
      # Seq
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://projectflow.seq:5341/ingest/otlp
      # - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      # Aspire Dashboard
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://projectflow.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      
  projectflow.postgres:
    image: postgres:17.2
    environment:
      POSTGRES_DB: projectflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  projectflow.seq:
    image: datalust/seq:2024.3
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ./.containers/seq_data:/data
    ports:
      - 8080:80
      - 5341:5341
  projectflow.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888